services:
  mysql1:
    restart: unless-stopped
    image: mysql
    command: '--log-bin --binlog-format=row --binlog-row-image=full'
    environment:
      MYSQL_ROOT_PASSWORD: root

  mysql2:
    restart: unless-stopped
    image: mysql
    command: '--log-bin --binlog-format=row --binlog-row-image=full'
    environment:
      MYSQL_ROOT_PASSWORD: root

  rw:
    restart: unless-stopped
    image: risingwavelabs/risingwave:v1.6.0
    command: playground
    ports:
      - '4566:4566'
      - '5691:5691'

  es:
    restart: unless-stopped
    image: 'docker.elastic.co/elasticsearch/elasticsearch:8.10.2'
    environment:
      ES_JAVA_OPTS: '-Xms2g -Xmx2g'
      discovery.type: 'single-node'
      xpack.security.enabled: 'false'
    ports:
      - '9200:9200'

  pubsub-emulator:
    image: gcr.io/google.com/cloudsdktool/google-cloud-cli:emulators
    command: gcloud beta emulators pubsub start --host-port=0.0.0.0:8085 --log-http --verbosity debug --user-output-enabled
    ports:
      - '8085:8085'

  debezium:
    restart: unless-stopped
    image: debezium/server:2.5
    volumes:
      - ./debezium:/debezium/conf

volumes:
  debezium: ~